### ISSUE TITLE
Platform configuration

### ISSUE THREAD

**Issue by drewcrawford** [AnarchyTools/atbuild#2]
There's been some discussion about how we implement this, I'm not sure a decision has been made.

We're currently faking this by violating DRY with separate tasks (e.g. compare "bootstrap" vs "default" in atbuild.yaml, they differ by one line).

**Comment by drewcrawford** [comment]
```
:profiles {
  :link-foundation [:linkflags -"lFoundation"]
  :linux {:deps ["build-linux-deps"] }
}
:tasks {
  :build-foo {:profile = "link-foundation" }
  :build-bar {:profile = "link-foundation" }
  :build-baz { }
}
```

**Comment by owensd** [comment]
I think it makes more sense to think of "profiles" versus "platforms". The problem with platform is that it implies a uniformity that isn't really present. Just because a target is being built on linux, it doesn't then follow that all of the settings are shared.

By convention, I think should say that platforms are just a config and they should take the values of: "linux", "osx", "ios", "win32", etc...

Related: Issue #8.

**Comment by drewcrawford** [comment]
This is blocked by #8.
