### ISSUE TITLE
Overlays, a better configuration

### ISSUE THREAD

**Issue by drewcrawford** [AnarchyTools/atbuild#24]
So I'm looking at packaging libdispatch with atbuild.

It turns out we can do this, but we need a long string of hacks on the client side (link side). We've got to inject a ton of flags.

My suggestion is that we say in dispatch's atbuild:

``` clojure
:mixins {
       :compile-osx {
              compileOptions: ["long" "list" "of" "hacks"]
        }
}
```

and then the client can say

``` clojure
: build {
     :tool "atllbuild"      ;; usual
     :src ["src/**.swift"] ;;suspects
     ;; and then
     :mixin ["dispatch.compile-osx"]
}
```

to import all the hacks.

We allow an unlimited number of mixins, which are just appended in-order.

We can move configurations to list their own mixins, like:

``` clojure
: mixins {
      :wholemodule {:compileFlags ["-Owholemodule"] }
}
: build {
     :tool "atllbuild"      ;; usual
     :src ["src/**.swift"] ;;suspects
     :configurations {
        :optimized {:yes ["wholemodule"]}
}
```

This has the best of both worlds, since mixins can be used across exactly those targets that are necessary.

**Comment by owensd** [comment]
Taks should simply have a configuration value that dictates the default configs to use. The intent is that command line and settings just merge together.

**Comment by drewcrawford** [comment]
I don't understand. Say again longer?

**Comment by owensd** [comment]
I will when I get a chance later this evening. :)

**Comment by drewcrawford** [comment]
In the meantime, I will prototype this on a branch.  I have a POC for packaging libdispatch on both platforms, it's just a matter of injecting the 10 or so flags into clients that link it.

**Comment by drewcrawford** [comment]
I've got a [sketch](https://github.com/AnarchyTools/atpkg/blob/mixins/tests/collateral/mixins.atpkg) of this along with the associated [tests](https://github.com/AnarchyTools/atpkg/blob/mixins/tests/model/PackageTests.swift#L62).

I still need to solve the case where mixins are exported across files.

**Comment by drewcrawford** [comment]
atpkg's [mixins](https://github.com/AnarchyTools/atpkg/tree/mixins) branch has a fairly complete implementation of this.  We do need to clean up some APIs and the docs if we merge.

I'd like to get some solution to this problem merged relatively soon; packaging libdispatch should be a priority for us, and it's the only issue preventing me from dogfooding `atbuild` in another project.

**Comment by owensd** [comment]
Ok, so at a high-level, this is roughly what I had in mind for the design. However, the implementation details differ from what I expected it would be.

Each task being built has a map of values that it uses to pass to the `tool` that is building it. However, there are some things to note:
1. It's important to be able to share these mapped values across multiple tasks
2. It's important to be able to override these values

An example usage might look like this:

```
$ atbuild atpkg-lib --profile osx --linkFlags "--framework Foundation"
```

This allows us to use all of the default values from the profile `osx` and append to the `linkFlags` setting from the command line. The key piece here is that _both_ of these flags are simply appending values to the `atpkg-lib` settings map.

Since appending is the typical case, it has the nicer syntax. For replacing and removing, we need a bit more information.

```
$ atbuild atpkg-lib --set profile osx --remove linkFlags "--framework Foundation"
```

The above line would replace whatever the `profile` value was a set it to _only_ be `osx`, and it would remove the `--framework Foundation` from the `linkFlags` value list.

So again, the concept is that this data simply flows through the system. In a `atpkg` file, the profiles are given a name via a key into the `profiles` map.

```
:profiles {
    :macosx {
        ;; all of the settings here
    }
}
```

Further, a build task can specify that it should make use of one of these profiles by default.

```
:tasks {
    :atpkg-lib-macosx {
        :profile ["macosx"]
        ;; all the other settings
    }
}
```

Now... I see what you're doing is fairly close, but it suffers from having to learn too many different concepts to get it to apply. For instance, you have two concepts that are the same thing: the top-level `mixins` and the `configurations` within the task. Then you have the property `mixins` on the task which is _not_ the same as the top-level `mixins` structure, but instead, an array mapping into the keys to apply to the task.

I think we can mostly change some terminology to get the design consistency I was hoping for, remove ambiguities around terms, and provide the task-level setting as well.

So I'd change your [mixins.atkpkg](https://github.com/AnarchyTools/atpkg/blob/mixins/tests/collateral/mixins.atpkg) to this:

```
(package
  :name "mixin"
  :version "0.1.0-dev"

  :profiles {
    :profile-one {
      :compileOptions ["-D" "MORE_AWESOME"]
    }
    :profile-two {
      :compileOptions ["-D" "MOST_AWESOME"]
    }
  }

  :tasks {
    :build {
      :tool "lldb-build"
      :profile ["profile-one"]
      ;; allow the setting of inner-profiles only available for the given task.
      :profiles {
        :awesome {
          :profile ["profile-two"]
        }
      }

      :name "json-swift"
      :output-type "lib" 
      :source [ "src/**.swift" "lib/**.swift" ]
      :compileOptions ["-D" "AWESOME"]
    }
  }
)
```

This provides the design consistency of the following:
1. All command-line parameters can be thought of the `CLI` profile.
2. A package file can have a set of shared profiles available for all tasks within the package, including imports.
3. A task can specify a set of profiles available only to itself.

This also specifies a very easy to understand priority mechanism: task -> profile -> command line. So the base values come from the task profile. The package file profile then modifies those values. Finally, the command line modifies the remaining values. This simplifies the code as well because the actual values are not determined until the final use and then it's basically, `merge(cli, package, task)`. Further, adding another profile, like a "project settings" profile is really trivial as well.

As for naming, I don't like the term `mixin` because it's much more than that. We provide (or will rather), the ability to append, remove, and replace values. Also, people generally aren't familiar with that term.

I don't like `configuration` as it has an implication of being one thing. For example, it's the macosx configuration or the linux configuration. In reality, it is more like: macosx, swift-toolchain, user "configurations". That's why I think profiles is better.

**Comment by drewcrawford** [comment]
This is all really good, thanks.  This is why we do design reviews.

It was not immediately clear to me how it was possible to unify the CLI and the top-level strings, but I see it now.

> As for naming, I don't like the term mixin because it's much more than that. We provide (or will rather), the ability to append, remove, and replace values. Also, people generally aren't familiar with that term.
> 
> I don't like configuration as it has an implication of being one thing. For example, it's the macosx configuration or the linux configuration. In reality, it is more like: macosx, swift-toolchain, user "configurations". That's why I think profiles is better.

Now that I see the full picture, I prefer the term "overlay".  You can definitely have more than one `overlay` whereas I think there is confusion on this point for configurations and profiles.  `overlay` also carries the idea that the order of operation is significant.  

Finally, an `overlay` can both hide, expose, or append to the thing it overlays.

I'm going to implement enough of this to get libdispatch packaged.
