### ISSUE TITLE
Creation of `.d` and `.o` files in a package root?

### ISSUE THREAD

**Issue by dunkelstern** [AnarchyTools/atbuild#92]
Is this only on my machines or where do those `*.d` and `*.o` files come from?

![screen shot 2016-05-09 at 23 35 03](https://cloud.githubusercontent.com/assets/456385/15128898/b515472a-163e-11e6-99e6-d2e1f13f7749.png)

**Comment by drewcrawford** [comment]
We emit these as a workaround for WMO, which is terribly broken upstream at present.  I have recently discovered our workaround is imperfect, so WMO with atbuild is not as fast as WMO from Xcode.

Upstream will fix their bug in next snapshot, so we will be able to remove our hack then, and also get better-performing WMO.

Self-assigning since I'm best-equipped to resolve this, but I intend to wait until a new snapshot.
